services:
  db:
    image: postgres:15
    container_name: ipz_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperHaslo1337
      POSTGRES_DB: marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ipz_backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=marketplace;Username=postgres;Password=SuperHaslo1337
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ipz_frontend

  nginx-proxy:
    image: nginx:alpine
    container_name: ipz_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_certs:/etc/nginx/certs
    command: >
      /bin/sh -c "
      apk add --no-cache openssl &&
      mkdir -p /etc/nginx/certs &&
      if [ ! -f /etc/nginx/certs/selfsigned.crt ]; then
        echo 'Generowanie certyfikatu SSL...' &&
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/selfsigned.key -out /etc/nginx/certs/selfsigned.crt -subj '/C=PL/ST=WestPomerania/L=Szczecin/O=IPZ/CN=localhost';
      fi &&
      nginx -g 'daemon off;'
      "
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  nginx_certs: